# permissions for end users to view appmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appmonitor-viewer-role
rules:
- apiGroups:
  - app-monitoring.galexrt.moe
  resources:
  - appmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app-monitoring.galexrt.moe
  resources:
  - appmonitors/status
  verbs:
  - get
